=== ScottLogic/data-engineering-generator/json/datahelix.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://scottlogic.com/datahelix.json",
  "definitions": {
    "schemaVersion": {
      "type": "string",
      "title": "The version of the DataHelix profile schema",
      "pattern": "^[0-9]+.[0-9]+$"
    },
    "temporal": {
      "type": "object",
      "properties": {
        "additionalProperties": false,
        "date": {
          "type": "string",
          "pattern": "^[0-9]{4}-[0-1][0-9]-([0-2][0-9]|3[01])T([0-1][0-9]|2[03]):[0-5][0-9]:[0-5][0-9].[0-9]{3}$"
        }
      }
    },
    "ofTypeValue": {
      "type": "object",
      "properties": {
        "additionalProperties": false,
        "value": {
          "type": "string",
          "enum": [
            "integer",
            "decimal",
            "string",
            "temporal"
          ]
        }
      }
    },
    "fieldNameFormat": {
      "type": "string",
      "title": "The name fo a field to generate data for",
      "pattern": "^([a-zA-Z][a-zA-Z0-9_\\s]*)$"
    },
    "grammaticalConstraint": {
      "oneOf": [
        {
          "$ref": "#/definitions/notConstraint"
        },
        {
          "$ref": "#/definitions/anyOfConstraint"
        },
        {
          "$ref": "#/definitions/allOfConstraint"
        },
        {
          "$ref": "#/definitions/ifConstraint"
        }
      ]
    },
    "presentationalConstraint": {
      "oneOf": [
        {
          "$ref": "#/definitions/formattedAs"
        }
      ]
    },
    "epistemicConstraint": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "field": {
          "$ref": "#/definitions/fieldNameFormat"
        },
        "is": {
          "oneOf": [
            {
              "$ref": "#/definitions/anyOfConstraint"
            },
            {
              "$ref": "#/definitions/notConstraint"
            },
            {
              "$ref": "#/definitions/allOfConstraint"
            },
            {
              "$ref": "#/definitions/ifConstraint"
            },
            {
              "$ref": "#/definitions/epistemicConstraint"
            }
          ]
        }
      }
    },
    "constraint": {
      "oneOf": [
        {
          "$ref": "#/definitions/grammaticalConstraint"
        },
        {
          "$ref": "#/definitions/presentationalConstraint"
        },
        {
          "$ref": "#/definitions/epistemicConstraint"
        }
      ]
    },
    "formattedAs": {
      "type": "string",
      "pattern": "^%.+$"
    },
    "notConstraint": {
      "not": {"$ref": "#/definitions/constraint"}
    },
    "anyOfConstraint": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "anyOf"
      ],
      "properties": {
        "anyOf": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/constraint"
          }
        }
      }
    },
    "allOfConstraint": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "allOf"
      ],
      "properties": {
        "allOf": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/constraint"
          }
        }
      }
    },
    "ifConstraint": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "if",
        "then"
      ],
      "properties": {
        "if": {
          "type": "object"
        },
        "then": {
          "type": "object"
        }
      }
    }
  },
  "type": "object",
  "title": "The Scott Logic DataHelix Profile Schema",
  "required": [
    "schemaVersion",
    "fields",
    "rules"
  ],
  "properties": {
    "additionalProperties": false,
    "schemaVersion": {
      "$ref": "#/definitions/schemaVersion"
    },
    "description": {
      "type": "string",
      "title": "A description of what data the profile is modelling",
      "pattern": "^(.*)$"
    },
    "fields": {
      "type": "array",
      "minItems": 1,
      "additionalItems": false,
      "title": "Defines the fields that data will be produced for. field names must begin with an alphabetic character.",
      "items": {
        "type": "object",
        "title": "A set of Field objects",
        "required": [
          "name"
        ],
        "properties": {
          "additionalProperties": false,
          "name": {
            "$ref": "#/definitions/fieldNameFormat"
          }
        }
      }
    },
    "rules": {
      "type": "array",
      "minItems": 1,
      "additionalItems": false,
      "title": "The Rules defining the data to be output",
      "items": {
        "type": "object",
        "title": "A set of Rule objects.",
        "required": [
          "constraints"
        ],
        "properties": {
          "additionalProperties": false,
          "rule": {
            "type": "string",
            "title": "A named collection of constraints. Test case generation revolves around rules, in that the generator will output a separate dataset for each rule, wherein each row violates the rule in a different way.",
            "pattern": "^([a-zA-Z][A-Za-z0-9:@~;'#,.Â£$%&\"\\s]+[.?!]*)$"
          },
          "constraints": {
            "type": "array",
            "minItems": 1,
            "additionalItems": false,
            "title": "The constraints defining the enclosing rule.",
            "items": {
              "$ref": "#/definitions/constraint"
            }
          }
        }
      }
    }
  }
}

=== ScottLogic/data-engineering-generator/orchestrator/src/test/java/com/scottlogic/deg/orchestrator/endtoend/testprofile.profile.json
{
    "schemaVersion": "0.10",
    "description": "Testing Profile",
    "fields": [
        {
          "name": "foo",
          "type": "string",
          "nullable": false
        }
    ],
    "rules": [
        {
            "rule": "rule1",
            "constraints": [
                {
                    "field": "foo",
                    "is": "equalTo",
                    "value": "Generation successful"
                }
            ]
        }
    ]
}

=== ScottLogic/data-engineering-generator/generator/src/test/profiles/input/TestProfile2.json
{
	"schemaVersion": "v3",
	"description": "Test 2",
	"fields": 
	[
		{ "name": "Parameter" },
		{ "name": "GraphType" },		
		{ "name": "User" },
		{ "name": "EventType" },
		{ "name": "UserType" }
	],
	"rules": [{
		"rule": "Parameter",
		"constraints": [{
			"field": "Parameter",
			"is": "inSet",
			"values": [
				"A",
				"B",
				"C"
			]
		},{
			"not": {
				"field": "Parameter",
				"is": "null"
			}
		}]
	},{
		"rule": "GraphType",
		"constraints": [{
			"field": "GraphType",
			"is": "inSet",
			"values": [
				"GraphType1",
				"GraphType2",
				"GraphType3",
				"GraphType4"
			]
		},{
			"not": {
				"field": "GraphType",
				"is": "null"
			}
		},{
			"if": {
				"allOf": [{
					"field": "Parameter",
					"is": "equalTo",
					"value": "A"
				}]
			},
			"then": {
				"allOf": [{
					"field": "GraphType",
					"is": "inSet",
					"values": [
						"GraphType2",
						"GraphType4"
					]
				}]
			}
		},{
			"if": {
				"allOf": [{
					"field": "Parameter",
					"is": "equalTo",
					"value": "C"
				}]
			},
			"then": {
				"allOf": [{
					"field": "GraphType",
					"is": "inSet",
					"values": [
						"GraphType2",
						"GraphType3"
					]
				}]
			}
		}]
	},{
		"rule": "User",
		"constraints": [{
			"field": "User",
			"is": "ofType",
			"value": "string"
		},{
			"not": {
				"field": "User",
				"is": "null"
			}
		},{
			"field": "User",
			"is": "shorterThan",
			"value": 50
		},{
			"if": {
				"allOf": [{
					"field": "UserType",
					"is": "equalTo",	
					"value": "UserTypeA"
				}]				
			},
			"then": {
				"allOf": [{
					"field": "User",
					"is": "inSet",
					"values": [
						"Administrator",
						"Moderator",
						"Editor"
					]
				}]
			}
		},{
			"if": {
				"allOf": [{
					"field": "UserType",
					"is": "inSet",
					"values": [
						"UserTypeB",
						"UserTypeC"
					]
				}]
			},
			"then": {
				"allOf": [{
					"field": "User",
					"is": "shorterThan",
					"value": 20
				}]
			}
		}]
	},{
		"rule": "EventType",
		"constraints": [{
			"field": "EventType",
			"is": "ofType",
			"value": "numeric"
		},{
			"field": "EventType",
			"is": "lessThan",
			"value": 40
		},{
			"if": {
				"allOf": [{
					"field": "Parameter",
					"is": "equalTo",
					"value": "B"
				}]
			},
			"then": {
				"allOf": [{
					"field": "EventType",
					"is": "inSet",
					"values": [
						10,
						15,
						20,
						30,
						35
					]
				}]
			}
		}]
	},{
		"rule": "UserType",
		"constraints": [{
			"field": "UserType",
			"is": "inSet",
			"values": [
				"UserTypeA",
				"UserTypeB",
				"UserTypeC",
				"UserTypeD"
			]
		},{
			"not": {
				"field": "UserType",
				"is": "null"
			}
		}]
	}]
}

=== ScottLogic/data-engineering-generator/profile/src/test/resources/test-profiles/valid/constraints-nested-inside-allof.json
{
  "schemaVersion": "0.1",
  "description": "profile description",
  "rules": [
    {
      "rule": "rule 1",
      "constraints": [
        {
          "allOf": [
            {
              "field": "field1",
              "is": "ofType",
              "value": "string"
            },
            {
              "field": "field2",
              "is": "greaterThan",
              "value": 43
            }
          ]
        }
      ]
    }
  ],
  "fields": [
    {
      "name": "field1"
    },
    {
      "name": "field2"
    }
  ]
}

=== ScottLogic/data-engineering-generator/generator/src/test/profiles/input/TestProfile1.json
{
	"schemaVersion": "v3",
	"description": "DTCC",
	"fields":
	[
		{ "name": "Level" },
		{ "name": "Type" },
		{ "name": "Identifier" },
		{ "name": "Event" }
	],
	"rules": [{
		"rule": "Level",
		"constraints": [{
			"field": "Level",
			"is": "inSet",
			"values": [
				"First",
				"Second",
				"Third",
				"Fourth",
				"Fifth"
			]
		},{
			"not": {
				"field": "Level",
				"is": "null"
			}
		},{
			"if": {
				"allOf": [{
					"field": "Type",
					"is": "inSet",
					"values": [
						"A",
						"B"
					]
				}]
			},
			"then": {
				"allOf": [{
					"field": "Level",
					"is": "inSet",
					"values": [
						"Second",
						"Third"
					]
				}]
			}
		},{
			"if": {
				"allOf": [{
					"field": "Type",
					"is": "inSet",
					"values": [
						"C"
					]
				}]
			},
			"then": {
				"allOf": [{
					"field": "Level",
					"is": "equalTo",
					"value": "First"
				}]
			}
		}]
	},{
		"rule": "Type",
		"constraints": [{
			"field": "Type",
			"is": "inSet",
			"values": [
				"A",
				"B",
				"C",
				"D",
				"E"
			]
		}]
	},{
		"rule": "Identifier",
		"constraints": [{
			"field": "Identifier",
			"is": "inSet",
			"values": [
				"EventA",
				"EventB",
				"EventC"
			]
		}]
	},{
		"rule": "Event",
		"constraints": [{
			"field": "Event",
			"is": "ofType",
			"value": "string"
		},{
			"field": "Event",
			"is": "shorterThan",
			"value": 10
		},{
			"if": {
				"allOf": [{
					"field": "Identifier",
					"is": "equalTo",
					"value": "EventB"
				}]
			},
			"then": {
				"field": "Event",
				"is": "shorterThan",
				"value": 20
			}
		}]
	}]
}
